name: flutter_devlog
description: A production-grade, zero-dependency custom logger for Dart and Flutter.
version: 1.0.0
repository: https://github.com/yibeltal-gashaw/packages/flutter-devlog.git
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Zero runtime dependencies for maximum efficiency and security.

dev_dependencies:
  test: ^1.24.0
